### PR TITLE
feat: integrate pre-commit/create replica with extrinsic call on pipeline

### LINKED ISSUE #472: Sector number should be generated by the Storage Provider.
Sector number can (and should) already be generated by the Storage Provider.
It is [accepted by Storage Provider Pallet](https://github.com/eigerco/polka-storage/blob/e9763ff2826e48f1099f74973cb12f66ce5bc0d8/pallets/storage-provider/src/sector.rs#L19) and it's internal numbering of the Storage Provider Node.
When we're doing with integrating the PoRep, we'll take sector number from Sector Data stored on chain and use it to prove. 
This is not blocked, and I don't want you to do this in this PR, but this can be a certainly a next task to do.

_Originally posted by @th7nder in https://github.com/eigerco/polka-storage/pull/470#discussion_r1814752396_

### LINKED ISSUE #474: Define a better ID for sector storage
Most likely we should not store it as `piece_cid`, as sector will contain multiple pieces, but by a SectorId,

_Originally posted by @th7nder in https://github.com/eigerco/polka-storage/pull/470#discussion_r1814757005_

### LINKED ISSUE #476: Call pre-commit after sealing a sector

### LINKED ISSUE #489: Separate out AddPiece pipeline step
Notes to consider / Food for thought:
* We'll eventually need to make this `AddPiece` where each piece is added to the pipeline for first accumulation into a sector and then pre-commited — maybe we should add that step now and avoid more changes in this place, but the trade off is making this PR more complex. Raising these issues with comments works too
* We'll probably be better off using a single `AddPieces` which has a batch, but I'm not sure

_Originally posted by @jmg-duarte in https://github.com/eigerco/polka-storage/pull/483#discussion_r1821141902_

### PR DESCRIPTION
**Pull request by th7nder**
### Description

Fixes #476, #474, #472, #489.

```
$ cargo build --release -p storagext-cli -p polka-storage-provider-client -p polka-storage-provider-server 
$ just testnet
[..] wait a sec till charlie boots up
$ ./examples/rpc_publish.sh examples/random1024.piece 
```

```
2024-10-31T17:37:27.379069Z  INFO precommit: polka_storage_provider_server::pipeline: Successfully pre-commited sectors on-chain: [SectorsPreCommitted { owner: AccountId32([144, 181, 171, 32, 92, 105, 116, 201, 234, 132, 27, 230, 136, 134, 70, 51, 220, 156, 168, 163, 87, 132, 62, 234, 207, 35, 20, 100, 153, 101, 254, 34]), sectors: BoundedVec([SectorPreCommitInfo { seal_proof: StackedDRG2KiBV1P1, sector_number: 1, sealed_cid: BoundedVec([1, 130, 226, 3, 129, 232, 2, 32, 5, 125, 210, 204, 219, 75, 0, 180, 103, 151, 95, 121, 224, 168, 58, 191, 50, 30, 6, 234, 11, 245, 135, 92, 66, 222, 132, 236, 161, 47, 60, 88]), seal_randomness_height: 17, deal_ids: BoundedVec([0]), expiration: 270, unsealed_cid: BoundedVec([1, 129, 226, 3, 146, 32, 32, 237, 215, 149, 223, 20, 39, 44, 248, 21, 68, 160, 135, 164, 200, 31, 3, 93, 170, 161, 203, 134, 237, 192, 210, 52, 108, 54, 123, 108, 99, 110, 16]) }]) }]
2024-10-31T17:37:27.379118Z  INFO polka_storage_provider_server::pipeline: Precommit for sector 1 finished successfully.


```

### Important points for reviewers

Add some additional resources that could help the reviewer with the
review. Like link to specs if implementing a protocol.

### Checklist

- [ ] Are there important points that reviewers should know?
  - [ ] If yes, which ones?
- [ ] Make sure that you described what this change does.
- [ ] Have you tested this solution?
- [ ] Follow-ups:
    - [ ] #493
    - [x] #491
    - [x] #496 
    - [x] #497 
- [ ] Were there any alternative implementations considered?
- [ ] Did you document new (or modified) APIs?

### CODE REVIEW

**Review by jmg-duarte — COMMENTED** [review]
Seems to me this is going in the right direction

**Review by jmg-duarte — COMMENTED** [review]
Right track, some items for discussion and some things to do.

Great job 🚀

**Review by jmg-duarte — COMMENTED** [review]
Amazing progress

**Review by jmg-duarte — DISMISSED** [review]

**Review by cernicc — APPROVED** [review]
Good job! 💪

**Review by jmg-duarte — APPROVED** [review]

**Pull request merged**
